apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-monkey-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-monkey-role
  namespace: corpora
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-monkey-depl-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments, statefulsets, daemonsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-monkey-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-monkey-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: kube-monkey-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-monkey-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-monkeyi-depl-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: kube-monkey-sa
  namespace: corpora
